platform :ios, '7.0'
inhibit_all_warnings!

target 'HitronWifi' do
pod 'AFNetworking',              '~> 3.0'
pod 'MBProgressHUD',             '~> 0.9.1'
pod 'MJExtension',               '~> 2.5.12'
pod 'MJRefresh',                 '~> 2.4.11'
pod 'Masonry',                   '~> 0.6.3'
pod 'SDWebImage',                '~> 3.7'
end
